-- 1. Create the requests table with location support
CREATE TABLE IF NOT EXISTS requests (
    id bigint generated by default as identity primary key,
    description text not null,
    size text not null,
    requester_email text not null,
    latitude double precision,
    longitude double precision,
    created_at timestamp with time zone default now()
);

-- 2. Create the donations table with location support
CREATE TABLE IF NOT EXISTS donations (
    id bigint generated by default as identity primary key,
    description text not null,
    quantity text not null,
    donor_email text not null,
    latitude double precision,
    longitude double precision,
    created_at timestamp with time zone default now()
);

-- 3. UNLOCK BOTH TABLES (Fixes the "Row Level Security" error)
ALTER TABLE requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE donations DISABLE ROW LEVEL SECURITY;

-- 4. Create collection_points table
CREATE TABLE IF NOT EXISTS collection_points (
    id bigint generated by default as identity primary key,
    name text not null,
    snippet text,
    latitude double precision not null,
    longitude double precision not null,
    created_at timestamp with time zone default now()
);

ALTER TABLE collection_points DISABLE ROW LEVEL SECURITY;

-- 5. Insert some sample collection points (Nairobi area - these can be anywhere)
INSERT INTO collection_points (name, snippet, latitude, longitude)
VALUES
('City Center Collection Point', 'Open 8am - 5pm', -1.28, 36.82),
('Westlands Recycling Hub', 'Open 24/7', -1.30, 36.78),
('Eastlands Community Box', 'Drop off anytime', -1.32, 36.85)
ON CONFLICT DO NOTHING;
